DROP TABLE IF EXISTS loans;

DROP TABLE IF EXISTS customer;

CREATE TABLE IF NOT EXISTS customer (
    tckn BIGINT PRIMARY KEY NOT NULL,
    name CHARACTER VARYING(255),
    last_name CHARACTER VARYING(255),
    monthly_salary DOUBLE PRECISION,
    phone_number CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_date TIMESTAMP WITHOUT TIME ZONE,
    approval_status BOOLEAN NOT NULL,
    loan_amount DOUBLE PRECISION,
    customer_tckn BIGINT,
    FOREIGN KEY (customer_tckn) REFERENCES customer (tckn)
);

INSERT INTO customer (name,last_name,tckn,phone_number,monthly_salary)
VALUES
    ('Ainsley','Hopper',10000000850,'8794964085',5369),
    ('Thor','Parks',10000000950,'8343458383',6676),
    ('Merritt','Woods',10000000050,'6154776828',6858),
    ('Bruno','Avila',10000000810,'3757713291',4934),
    ('Sacha','Ashley',10000000910,'8542845257',3975),
    ('Hayes','Willis',10000000010,'1724644137',4887);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2021-03-08 21:38:39.161','true',20000,10000000850),
    ('2022-01-16 22:33:52.164','false',0,10000000850),
    ('2022-02-12 20:52:08.164','true',10000,10000000850);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2022-12-20 16:24:16.1671542656','false',0,10000000950),
    ('2021-06-09 12:32:03.1623231123','true',20000,10000000950),
    ('2023-01-29 20:37:00.1675013820','true',24520,10000000950);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2022-03-23 18:45:09.1648050309','false',0,10000000050),
    ('2021-07-20 00:16:36.1626729396','false',0,10000000050);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2022-12-30 23:31:11.1672432271','true',10000,10000000810);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2022-11-30 06:22:01.1669778521','true',15900,10000000910),
    ('2021-10-13 10:44:42.1634111082','false',0,10000000910),
    ('2021-05-27 09:29:03.1622096943','true',15100,10000000910);

INSERT INTO loans (approval_date,approval_status,loan_amount,customer_tckn)
VALUES
    ('2021-10-13 10:44:42.1634111082','false',0,10000000010),
    ('2022-11-03 15:26:32.1667478392','false',0,10000000010);